name: "Test composite action"
description: "Test how composite actions behave in a workflow"
inputs:
  folder:
    description: "Folder to execute the command in"
    required: true
    default: "~"
  command:
    description: "command to apply"
    required: true
    default: "apply"    
runs:
  using: "composite"
  steps: 
    - name: Echo action inputs
      run: echo "Running ${{ inputs.command }} in target folder ${{ inputs.folder }}"
      shell: bash
      
    - name: Set target environment
      run: echo ::set-env name=ENV_TARGET::$([[ "${GITHUB_REF}" =~ ^refs/tags/.* ]] && echo prod || echo test)
      shell: bash
      
    - name: Check target environment 
      run: echo "Deploying to ${{ env.ENV_NAME_BASE }}${{ env.ENV_TARGET }}"
      shell: bash

    - name: Run script in parent action
      run: /tf/rover/rover.sh logout
      shell: bash
